server:
  port: 9094

eureka:
  instance:
    hostname: localhost
    port: 9091
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 'root'
        platform: mysql
        url: jdbc:mysql://localhost:3306/squadcollab_ideia?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true

authserver:
  hostname: http://localhost:9092/oauth
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
